### ISSUE TITLE
failing to use correct screenshots path assuming and adding 'screenshots' folder to all images

### ISSUE THREAD

**Issue by kirksl** [fijijavis/wdio-mochawesome-reporter#17] opened 2017-12-27 19:17 UTC
failing to use 'screenshotPath' property in wdio.conf.js for images taken by wdio testrunner
wdio-mochawesome-reporter adds 'screenshots' meanwhile 'screenshotPath' in wdio.conf.js could be set to './screenshots/errors'.  images are now broken in report.

failing to use path defined by developer for all other images
a developer may be calling browser.saveScreenshot(myPath) throughout a test where 'myPath' is user defined.  wdio-mochawesome-reporter adds 'screenshots' to 'myPath'.  images are now broken in report.

we have tested a fix in reporter.js below.  if we can get a fix and updated npm package we would greatly appreciate it.

const screenshotPath = this.config.screenshotPath.replace(/\/$/, "")

screenshotCommands.forEach(cmd => {
	if(cmd.payload.filename.indexOf(path.sep) === -1)
	{
		context.push({title: `Screenshot: ${cmd.payload.filename}`,value: path.join(screenshotPath,cmd.payload.filename)})
	}
	else
	{
		context.push({title: `Screenshot: ${cmd.payload.filename}`,value: cmd.payload.filename})
	}
});

**Comment by kirksl** [comment] 2017-12-28 19:22
temporary package published until this issue is fixed
https://www.npmjs.com/package/wdio-mochawesome-reporter-fixed

**Comment by fijijavis** [comment] 2017-12-28 20:56
@kirksl Sorry for the slow response.  I'm on vacation for the holidays and haven't spent much time on my computer.  Did you submit a PR for the issue?

**Comment by kirksl** [comment] 2017-12-29 00:26
@fijijavis no worries.  i needed a quick fix before end of year and created a temporary npm package(below).  i updated reporter.js with the code posted in the opening of this bug and it works perfect.  let me know if you have any questions on the code.

https://www.npmjs.com/package/wdio-mochawesomefixed-reporter

**Comment by mentierd** [comment] 2018-01-03 17:55
instead of creating a new node module, we should rely on npm to control the versioning.

**Comment by fijijavis** [comment] 2018-01-03 23:35
@mentierd agreed.  there will be a new version published with a proper semver bump.

**Comment by fijijavis** [comment] 2018-01-04 00:49
@kirksl 1.1.3 has been published for this fix

**Comment by marcelas** [comment] 2018-01-09 19:28
I believe the current implementation is still wrong, I have screenshotPath set ./output/screenshots and the outdir set to ./output. The current implementation is using ./output/output/screenshot as the image path

**Comment by marcelas** [comment] 2018-01-09 20:07
it looks like in the case where the filename contains a path, we are missing a path.resolve

**Comment by davidjgonzalez** [comment] 2018-10-02 19:50
I am seeing the same issue as @marcelas - and all my errorshots image urls are broken on my reports

**Comment by fijijavis** [comment] 2018-10-03 03:10
@davidjgonzalez what version of the reporter are you using?

**Comment by IgorLizenko** [comment] 2018-11-28 10:45
I have the same issue in 2.0.1 reporter

**Comment by GineaPig** [comment] 2018-12-22 20:33
I have the same issue in 2.0.1 reporter.

**Comment by IgorLizenko** [comment] 2019-01-11 16:56
@fijijavis could you reopen this issue? it still persists

**Comment by fijijavis** [comment] 2019-01-11 18:39
@igorlizenko done.  

Hoping I might have a chance to look at this soon.  If anyone has a solution already submit a PR.

**Comment by fijijavis** [comment] 2019-01-16 15:31
@IgorLizenko @GineaPig @davidjgonzalez @marcelas 

I am unable to reproduce this issue.  I have the following configuration 

`
reporterOptions: {
        outputDir: './output',
},
screenshotPath: './output/screenshots/',
`
Can someone post a reproducible test and config?

**Comment by marcinlesek** [comment] 2019-01-22 11:34
I have this same problem, also with your configuration @fijijavis 
```
screenshotPath: './reports/screenshots/',
reporterOptions: {
    outputDir: './reports',
  },
```
and now, in report I have `http://localhost:63342/project-dir/reports/reports/screenshots/ERROR_chrome_2019-01-22T11-31-16.188Z.png` instead of `http://localhost:63342/project-dir/reports/screenshots/ERROR_chrome_2019-01-22T11-31-16.188Z.png` which works fine and shows screenshot.

**Comment by fijijavis** [comment] 2019-01-22 13:39
@marcinlesek thanks for replying.  Are the screenshots where you see this ones that are auto captured by the wdio test runner Or are they ones you are manually capturing?

**Comment by marcinlesek** [comment] 2019-01-22 16:31
@fijijavis autocaptured with wdio runner on tests fail. If you have problem with reproduction, maybe versions of libs will help you:
```
    "mochawesome": "^3.1.1",
    "mochawesome-report-generator": "^3.1.4",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-mochawesome-reporter": "^2.0.1",
    "webdriverio": "^4.14.0"
```

**Comment by fijijavis** [comment] 2019-01-23 05:32
@marcinlesek Thanks again for the extra info.  Somehow, I am still unable to reproduce the issue.  What OS and what node versions are you using?  I'm MacOS 10.13.6 with node v10.13.0

**Comment by marcinlesek** [comment] 2019-01-23 17:27
@fijijavis MacOS Mojave `10.14.2`, node `v10.14.2` installed by `nvm`. What is a bit strange, in `wdiomochawesome.json` url looks good:
```
"context": "[{\"title\":\"Session Id\",\"value\":\"40fca36173ee253deea3f7c5f5b266c0\"},{\"title\":\"Screenshot: ERROR_chrome_2019-01-22T11-31-16.188Z.png\",\"value\":\"reports/screenshots/ERROR_chrome_2019-01-22T11-31-16.188Z.png\"}]",
```

In `wdiomochawesome.html` it also looks good, in `data-raw` attribute:
```
\&quot;value\&quot;:\&quot;reports/screenshots/ERROR_chrome_2019-01-22T11-31-16.188Z.png\&quot;}]&quot;
```
and in `data-config` attribute:
```
&quot;reportDir&quot;:&quot;reports&quot;
```
🤔

**Comment by ToygarM** [comment] 2019-02-22 15:49
Hello guys, i have the same particular issue. I don't get the png files in my mochawesome report to provide screenshots in the reporter. I see now broken images, because the filepath is incorrect! Only when i paste the screenshots manually  in the mochawesome-report path i see nicely the screenshots in the report showing. See below for details:

        mochawesome: {
          outputDir: './mochawesome-report',
          mochawesome_filename: 'wdiomochawesome.json',
        },
    mochawesomeOpts: {
      includeScreenshots:true,
      screenshotUseRelativePath:true,
  },

**Comment by fijijavis** [comment] 2019-05-21 13:12
Closing as this will not be an issue with the wdio v5 compatible version of the report

**Closed by fijijavis** 2019-05-21 13:12 UTC
Labels: under investigation
